#!/bin/sh
nohup ./run -prefix ~/lab/dataset -source YelpNew -set byUser_20k_review -crossV 5 -nuOfTopics 5 -emIter 50 -topicmodel RTM > ./output/5_YelpNew_RTM_5.output 2>&1 &
nohup ./run -prefix ~/lab/dataset -source YelpNew -set byUser_20k_review -crossV 5 -nuOfTopics 10 -emIter 50 -topicmodel RTM > ./output/5_YelpNew_RTM_10.output 2>&1 &
nohup ./run -prefix ~/lab/dataset -source YelpNew -set byUser_20k_review -crossV 5 -nuOfTopics 15 -emIter 50 -topicmodel RTM > ./output/5_YelpNew_RTM_15.output 2>&1 &
nohup ./run -prefix ~/lab/dataset -source YelpNew -set byUser_20k_review -crossV 5 -nuOfTopics 20 -emIter 50 -topicmodel RTM > ./output/5_YelpNew_RTM_20.output 2>&1 &
nohup ./run -prefix ~/lab/dataset -source YelpNew -set byUser_20k_review -crossV 5 -nuOfTopics 25 -emIter 50 -topicmodel RTM > ./output/5_YelpNew_RTM_25.output 2>&1 &
nohup ./run -prefix ~/lab/dataset -source YelpNew -set byUser_20k_review -crossV 5 -nuOfTopics 30 -emIter 50 -topicmodel RTM > ./output/5_YelpNew_RTM_30.output 2>&1 &
nohup ./run -prefix ~/lab/dataset -source YelpNew -set byUser_20k_review -crossV 5 -nuOfTopics 35 -emIter 50 -topicmodel RTM > ./output/5_YelpNew_RTM_35.output 2>&1 &
nohup ./run -prefix ~/lab/dataset -source YelpNew -set byUser_20k_review -crossV 5 -nuOfTopics 40 -emIter 50 -topicmodel RTM > ./output/5_YelpNew_RTM_40.output 2>&1 &
nohup ./run -prefix ~/lab/dataset -source YelpNew -set byUser_20k_review -crossV 5 -nuOfTopics 45 -emIter 50 -topicmodel RTM > ./output/5_YelpNew_RTM_45.output 2>&1 &
nohup ./run -prefix ~/lab/dataset -source YelpNew -set byUser_20k_review -crossV 5 -nuOfTopics 50 -emIter 50 -topicmodel RTM > ./output/5_YelpNew_RTM_50.output 2>&1 &
